server:
  port: 8083

spring:
  application:
    name: avatar-service
  datasource:
    url: ***REMOVED***_test
    username: student
    password: ***REMOVED***
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    rollback-file: classpath:liquibase/rollback/rollback.sql
  jackson:
    serialization:
      indent-output: true
  servlet:
    multipart:
      max-file-size: 10MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#Constants
path:
  to:
    avatars:
      folder: ./avatars
springdoc:
  packagesToScan: ru.hogwarts.avatar