server:
  port: 8083

spring:
  application:
    name: avatar
  datasource:
    url: ***REMOVED***_test
    username: student
    password: ***REMOVED***
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
  jackson:
    serialization:
      indent-output: true
  servlet:
    multipart:
      max-file-size: 10MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
#Constants
path:
  to:
    avatars:
      folder: ./avatars