-- liquibase formatted sql
-- changeset atrilos:1

CREATE TABLE student
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    age        INTEGER DEFAULT 20                      NOT NULL,
    faculty_id BIGINT,
    avatar_id  BIGINT UNIQUE,
    CONSTRAINT pk_student PRIMARY KEY (id),
    CONSTRAINT fk_student_on_faculty FOREIGN KEY (faculty_id)
        REFERENCES faculty,
    CONSTRAINT fk_student_on_avatar FOREIGN KEY (avatar_id)
        REFERENCES avatar
);
-- rollback DROP TABLE student;