-- liquibase formatted sql
-- changeset atrilos:1

CREATE TABLE avatar
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_path  VARCHAR(255),
    file_size  BIGINT                                  NOT NULL,
    media_type VARCHAR(255),
    data       BYTEA,
    CONSTRAINT pk_avatar PRIMARY KEY (id)
);
-- rollback DROP TABLE avatar;