server:
  port: 8080

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/hogwarts
    username: student
    password: chocolatefrog
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
  jackson:
      serialization:
        indent-output: true
  servlet:
    multipart:
      max-file-size: 10MB
#Constants
path:
  to:
    avatars:
      folder: /avatars