server:
  port: 8080
  error:
    include-message: always
spring:
  datasource:
    url: ***REMOVED***
    username: student
    password: ***REMOVED***
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        generate_statistics: true
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
  jackson:
    serialization:
      indent-output: true
  servlet:
    multipart:
      max-file-size: 10MB
logging:
  level:
    org:
      hibernate: INFO

#Constants
path:
  to:
    avatars:
      folder: ./avatars
