server:
  port: 8080

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
          filters:
            - RewritePath=/student/(?<path>.*), /$\{path}
        - id: faculty-service
          uri: lb://faculty-service
          predicates:
            - Path=/faculty/**
          filters:
            - RewritePath=/faculty/(?<path>.*), /$\{path}
        - id: avatar-service
          uri: lb://avatar-service
          predicates:
            - Path=/avatar/**
          filters:
            - RewritePath=/avatar/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
      discovery:
        locator:
          enabled: true

springdoc:
  swagger-ui:
    urls:
      - name: student
        url: /v3/api-docs/student
      - name: faculty
        url: /v3/api-docs/faculty
      - name: avatar
        url: /v3/api-docs/avatar

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka