server:
  port: 8081

spring:
  application:
    name: student-service
  datasource:
    url: ***REMOVED***_test
    username: student
    password: ***REMOVED***
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    rollback-file: classpath:liquibase/rollback/rollback.sql
  jackson:
    serialization:
      indent-output: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  packagesToScan: ru.hogwarts.avatar