server:
  port: 8080

spring:
  application:
    name: student
  datasource:
    url: ***REMOVED***
    username: student
    password: ***REMOVED***
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
  jackson:
    serialization:
      indent-output: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false