-- liquibase formatted sql
-- changeset atrilos:1

CREATE TABLE faculty
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    color VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_faculty PRIMARY KEY (id)
);
-- rollback DROP TABLE faculty;